language: en
autodownload: true
debug: false
firstRun: true
moneytoxp: 1.00
xptomoney: 1.00
onlysendxptoonlineplayers: false
buydeactivated: false
selldeactivated: false
senddeactivated: false
buyleveldeactivated: false
sellleveldeactivated: false
infodeactivated: false
helpdeactivated: false
infoxpdeactivated: false
infoleveldeactivated: false
Signscreatedeactivated: false
Signsusedeactivated: false
Signsdestroydeactivated: false
command:
  error:
    info:
      de: Du kannst maximal %1$d XP in %2$d Geld umwandeln.
      en: You can change maximal %1$d XP into %2$d money.
    buyinfo:
      de: Du kannst maximal %1$d Geld in %2$d XP umwandeln.
      en: You can change maximal %1$d money into %2$d XP.
    notenoughmoney:
      de: Du hast nicht genuegend Geld!
      en: Not enough money!
    notenoughxp:
      de: Du hast nicht genuegend XP!
      en: Not enough XP!
    else:
      de: Unbekannter Error!
      en: Error!
    noint:
      de: Falsche Eingabe!
      en: Wrong command!
    noargs0:
      de: Kein buy oder sell vorhanden!
      en: No buy or sell found!
    toomanyarguments:
      de: Dieser Befehl hat eine falsche Syntax!
      en: This command has an invalid syntax!
    fewargs:
      de: Zu wenig Argumente!
      en: Few arguments!
    noplayer:
      de: Du bist kein Player!
      en: You are no player!
  success:
    buy:
      de: Du hast %1$d Geld in %2$d XP umgewandelt. 
      en: You changed %1$d money into %2$d XP.
    sell:
      de: Du hast %1$d XP in %2$d Money umgewandelt. 
      en: You changed %1$d XP into %2$d money. 
    buylevel:
      de: Du hast %1$d Geld in %2$d XP umgewandelt. 
      en: You changed %1$d money into %2$d XP.
    selllevel:
      de: Du hast %1$d XP in %2$d Money umgewandelt. 
      en: You changed %1$d XP into %2$d money. 
    sentxp:
      de: Du hast %1$d XP zu %2$s gesendet.
      en: You sent %1$d XP to %2$s.
    recievedxp:
      de: Du hast %1$d XP von %2$s erhalten.
      en: You recieved %1$d XP from %2$s.
permissions:
  error:
    de: Wir haben ein Problem! Dies darfst Du nicht machen!
    en: we have a problem! You musnt do this!
  notfound:
    de: PermissionsEx plugin nicht gefunden!
    en: PermissionsEx not found!
iConomy:
  error:
    de: Kein iConomy5 oder 6 oder Register gefunden!
    en: No iConomy5 or 6 or Register found!
help: 
  buy:
    de: Wandelt Geld in XP um.
    en: Changes money into XP.
  buylevel:
    de: Wandelt Geld in Level um.
    en: Changes money into level.
  sell:
    de: Wandelt XP in Geld um.
    en: Changes XP into money.
  selllevel:
    de: Wandelt Level in Geld um.
    en: Changes level into money.
  info:
    de: Zeigt infos zu einer Action, die nicht ausgefuehrt wurde.
    en: Shows infos to an action, which is not performed.
  send:
    de: Sendet XP zu anderen Playern.
    en: Send XP to other players.
  infoxp:
    de: Zeigt aktuelle XP.
    en: Shows XP which a player have.
  infolevel:
    de: Zeigt aktuelle XP.
    en: Shows XP which a player have.
info:
  ownXP:
    de: Du hast %1$d XP.
    en: You have %1$d XP.
  otherXP:
    de: Player %1$s hat %2$d XP.
    en: Player %1$s has %2$d XP.
  ownLevel:
    de: Du hast %1$d Level.
    en: You have %1$d level.
  otherLevel:
    de: Player %1$s hat %2$d Level.
    en: Player %1$s has %2$d level.
  prefix:
    de: Info (nicht ausgefuehrt)
    en: Info (not performed)
Shop:
  success:
    buy:
      de: Du hast %1$s XP von %2$s fuer %3$s gekauft.
      en: You bought %1$s XP from %2$s for %3$s.
    sell:
      de: Du hast %1$s XP an %2$s verkauft fuer %3$s.
      en: You selled %1$s XP to %2$s for %3$s.
    sellerselled:
      de: Player %2$s hat an Dich %1$s XP fuer %3$s verkauft.
      en: Player %2$s has selled %1$s XP to you for %3$s.
    sellerbuy:
      de: Player %2$s hat von Dir %1$s XP fuer %3$s gekauft.
      en: Player %2$s has bought %1$s XP from you for %3$s.
  error:
    notenoughmoneyseller:
      de: Der Verkaufer hat nicht genuegend Geld!
      en: The seller hasnt enough money!
    notenoughmoneyconsumer:
      de: Du hast nicht genug Geld!
      en: You havent got enough money!
    notenoughxpseller:
      de: Der Verkaufer hat nicht genug XP!
      en: The seller hasnt enough XP!
    notenoughxpconsumer:
      de: Du hast nicht genuegend XP um an diesen Shop verkaufen zu koennen.
      en: You havent enough XP to be able to sell at this Shop.
    cantsellhere:
      de: Du kannst hier nicht verkaufen!
      en: You cant sell here!
    cantbuyhere:
      de: Du kannst hier nicht kaufen!
      en: You cant buy here!
playernotonline:
  de: war noch nicht hier!
  en: wasnt online before!
playerwasntonline:
  de: war noch nicht hier!
  en: wasnt online before!
onlyonlineplayer:
  de: es ist nur das managen von XP von Onlineplayern ist erlaubt.
  en: only managing of XP of online players allowed.