language: en
moneyplugin: 5
autodownload: true
moneytoxp: 1.00
xptomoney: 1.00
command:
  error:
    notenoughmoney:
      de: Du hast nicht genügend Geld!
      en: Not enough money!
    notenoughxp:
      de: Du hast nicht genügend XP!
      en: Not enough XP!
    else:
      de: Unbekannter Error!
      en: Error!
    noint:
      de: Falsche Eingabe!
      en: Wrong command!
    noargs0:
      de: Kein buy oder sell vorhanden!
      en: No buy or sell found!
    toomanyarguments:
      de: Dieser Befehl hat eine falsche Syntax!
      en: This command has an invalid syntax!
    fewargs:
      de: Zu wenig Argumente!
      en: Few arguments!
    noplayer:
      de: Du bist kein Player!
      en: You are no player!
  success:
    buy:
      de:
        1: Du hast 
        2: Money in 
        3: XP umgewandelt. 
      en:
        1: You changed 
        2: money into 
        3: XP. 
    sell:
      de:
        1: Du hast 
        2: XP in 
        3: Money umgewandelt. 
      en:
        1: You changed 
        2: XP into 
        3: money. 
    buylevel:
      de:
        1: Du hast 
        2: Money in 
        3: XP umgewandelt. 
      en:
        1: You changed 
        2: money into 
        3: XP. 
    selllevel:
      de:
        1: Du hast 
        2: XP in 
        3: Money umgewandelt. 
      en:
        1: You changed 
        2: XP into 
        3: money.
    sentxp:
      de: Du hast %s XP to %s gesendet.
      en: You sent %s XP to %s.
permissions:
  error:
    de: Houston Wir haben ein Problem! Diesen Befehl darfst Du nicht verwenden!
    en: Houston we have a problem! You can't use this command!
  notfound:
    de: PermissionsEx plugin nicht gefunden!
    en: PermissionsEx not found!
iConomy:
  error:
    de: Kein iConomy5 oder 6 oder Register gefunden!
    en: No iConomy5 or 6 or Register found!
help: 
  buy:
    de: Wandelt Geld in XP um.
    en: Changes money into XP.
  buylevel:
    de: Wandelt Geld in Level um.
    en: Changes money into level.
  sell:
    de: Wandelt XP in Geld um.
    en: Changes XP into money.
  selllevel:
    de: Wandelt Level in Geld um.
    en: Changes level into money.
  info:
    de: Zeigt infos zu einer Action, die nicht ausgefuehrt wurde.
    en: Shows infos to an action, wich is not performed.
info:
  prefix:
    de: Info (nicht ausgefuehrt)
    en: Info (not performed)