language: en
command:
  error:
    notenoughmoney:
      de: Du hast nicht genügend Geld!
      en: Not enough money!
    notenoughxp:
      de: Du hast nicht genügend XP!
      en: Not enough XP!
    else:
      de: Unbekannter Error!
      en: Error!
    noint:
      de: Konnte args[1] nicht in int wandeln!
      en: Couldn't parse arsgs[1] into an int!
    noargs0:
      de: Kein buy oder sell vorhanden!
      en: No buy or sell found!
    toomanyarguments:
      de: Dieser Befehl hat eine falsche Syntax!
      en: This command has an invalid syntax!
    fewargs:
      de: Zu wenig Argumente!
      en: Few arguments!
  success:
    buy:
      de:
        1: Du hast 
        2: Money in 
        3: XP umgewandelt. 
      en:
        1: You changed 
        2: money into 
        3: XP. 
    sell:
      de:
        1: Du hast 
        2: XP in 
        3: Money umgewandelt. 
      en:
        1: You changed 
        2: XP into 
        3: money. 
permissions:
  error:
    de: Houston Wir haben ein Problem! Diesen Befehl darfst Du nicht verwenden!
    en: Houston we have a problem! You can't use this command!
  notfound:
    de: PermissionsEx plugin nicht gefunden!
    en: PermissionsEx not found!
moneytoxp: 1.00
xptomoney: 1.00
iConomy5:
  error:
    de: Kein iConomy5 gefunden!
    en: No iConomy5 found!