language: en
command:
  error:
    else:
      de: Unbekannter Error!
      en: Error!
    noint:
      de: Konnte args[1] nicht in int wandeln!
      en: Couldn't parse arsgs[1] into an int!
    noargs0:
      de: Kein buy oder sell vorhanden!
      en: No buy or sell found!
    toomanyarguments:
      de: Dieser Befehl hat eine falsche Syntax!
      en: This command has an invalid syntax!
    fewargs:
      de: Zu wenig Argumente!
      en: Few arguments!
  success:
    moneytoxp:
      de: Du hast Money in XP umgewandelt.
      en: You changed money into XP.
    moneytoxpalt:
      de: Du hast "+ money +" in "+ TOTALXP +" XP umgewandelt.
      en: You changed "+ money +" into "+ TOTALXP +" XP.
    xptomoney:
      de: Du hast "+ TOTALXP +" XP in "+ money +"  umgewandelt.
      en: You changed "+ TOTALXP +" XP in "+ money +".
permissions:
  error:
    de: Houston Wir haben ein Problem! Diesen Befehl darfst Du nicht verwenden!
    en: Houston we have a problem! You can't use this command!
permissions:
  notfound:
    de: PermissionsEx plugin nicht gefunden!
    en: PermissionsEx not found!
moneytoxp: 1
xptomoney: 1