name:  xpShop
version:  1.9
description:  Player can buy xp
author:  ibhh
website: http://www.ibhh.de

main: me.ibhh.xpShop.xpShop

commands:
  xpShop:
    description: player gets xp for money.
    usage: /xpShop buy <xp|money>
permissions:
  xpShop.*:
    description: Gives access to all xpShop commands
    children:
      xpShop.buy: true
      xpShop.sell: true
      xpShop.buylevel: true
      xpShop.selllevel: true
      xpShop.info: true
      xpShop.send: true
      xpShop.infoxp.own: true
      xpShop.infoxp.other: true
      xpShop.infolevel.own: true
      xpShop.infolevel.other: true
  xpShop.buy:
    description: Allows you to buy xp.
    default: true
  xpShop.sell:
    description: Allows you to sell xp.
    default: true
  xpShop.buylevel:
    description: Allows you to buy level.
    default: true
  xpShop.selllevel:
    description: Allows you to sell level.
    default: true
  xpShop.info:
    description: gives you an info.
    default: true
  xpShop.help:
    description: gives you a help.
    default: true
  xpShop.send:
    description: send XP to other players.
    default: true
  xpShop.infoxp.own:
    description: Returns your XP amount.
    default: true
  xpShop.infolevel.own:
    description: Returns your level amount.
    default: true
  xpShop.infoxp.other:
    description: Returns your level amount of any player.
    default: true
  xpShop.infolevel.other:
    description: Returns level amount of any player.
    default: true