name:  xpShop
version:  0.1
description:  Player can buy xp
author:  ibhh
website: http://www.ibhh.de

main: me.ibhh.xpShop.xpShop

commands:
  xpShop:
    description: player gets xp for money.
    usage: /xpShop buy <xp> or /xpShop sell <money>
permissions:
  xpShop.*:
    description: Gives access to all xpShop commands
    children:
      xpShop.buy: true
      xpShop.sell: true
  xpShop.buy:
    description: Allows you to buy xp.
    default: true
  xpShop.sell:
    description: Allows you to sell xp.
    default: true