name: xpShop
version: 10.1
description: Managing of players XP
author: ibhh
website: http://ibhh.de/xpShop.jar
softdepend: [Vault]

main: me.ibhh.xpShop.xpShop

commands:
  xpShop:
    description: help of xpShop
    usage: /xpShop
permissions:
  xpShop.*:
    description: Gives access to all xpShop commands
    children:
      xpShop.buy: false
      xpShop.sell: false
      xpShop.buylevel: false
      xpShop.selllevel: false
      xpShop.info: false
      xpShop.send: false
      xpShop.infoxp.own: false
      xpShop.infoxp.other: false
      xpShop.infolevel.own: false
      xpShop.infolevel.other: false
      xpShop.debugfile: false
      xpShop.admin: false
      xpShop.deletetable: false
      xpShop.resetplayer: false
      xpShop.setxp: false
      xpShop.grand: false
      xpShop.tpto: false
      xpShop.tpme: false
      xpShop.tp: false
      xpShop.update: false
    default: false
  xpShop.buy:
    description: Allows you to buy xp.
    default: false
  xpShop.sell:
    description: Allows you to sell xp.
    default: false
  xpShop.buylevel:
    description: Allows you to buy level.
    default: false
  xpShop.selllevel:
    description: Allows you to sell level.
    default: false
  xpShop.info:
    description: gives you an info.
    default: false
  xpShop.help:
    description: gives you a help.
    default: false
  xpShop.send:
    description: send XP to other players.
    default: false
  xpShop.infoxp.own:
    description: Returns your XP amount.
    default: false
  xpShop.infolevel.own:
    description: Returns your level amount.
    default: false
  xpShop.infoxp.other:
    description: Returns your level amount of any player.
    default: false
  xpShop.infolevel.other:
    description: Returns level amount of any player.
    default: false
  xpShop.debugfile:
    description: Allows you to toggle debuging.
    default: false
  xpShop.admin:
    description: Allows you to do admin stuff.
    default: false
  xpShop.deletetable:
    description: Allows you to delete the xpShop table.
    default: false
  xpShop.resetplayer:
    description: Allows you to resets players XP.
    default: false
  xpShop.setxp:
    description: Allows you to set players xp.
    default: false
  xpShop.grand:
    description: Allows you to grand a mount of XP to a player
    default: false
  xpShop.tpto:
    description: Allows you to teleport to a player for XP
    default: false
  xpShop.tpme:
    description: Allows you to teleport a player to you
    default: false
  xpShop.tp:
    description: Allows you to accept a teleport.
    default: false
  xpShop.update:
    description: Allows you to update the plugin ingame.
    default: false