name: xpShop
version: 12.2
description: Managing of players XP
author: ibhh
website: http://ibhh.de/xpShop.jar
softdepend: [Vault]

main: me.ibhh.xpShop.xpShop

commands:
  xpShop:
    description: help of xpShop
    usage: /xpShop
permissions:
  xpShop.*:
    description: Gives access to all xpShop commands
    children:
      xpShop.reload: true
      xpShop.config: true
      xpShop.buy: true
      xpShop.sell: true
      xpShop.buylevel: true
      xpShop.selllevel: true
      xpShop.info: true
      xpShop.send: true
      xpShop.bottle: true
      xpShop.infoxp.own: true
      xpShop.infoxp.other: true
      xpShop.infolevel.own: true
      xpShop.infolevel.other: true
      xpShop.internet: true
      xpShop.version: true
      xpShop.debugfile: true
      xpShop.admin: true
      xpShop.deletetable: true
      xpShop.resetplayer: true
      xpShop.setxp: true
      xpShop.showdebug: false
      xpShop.grand: true
      xpShop.repair: true
      xpShop.report: true
      xpShop.toolinfo: true
      xpShop.tpto: true
      xpShop.tpme: true
      xpShop.tp: true
      xpShop.update: true
    default: op
  xpShop.reload:
    description: Allows you to reload the plugin.
    default: op
  xpShop.config:
    description: Allows you to change the config ingame.
    default: op
  xpShop.bottle:
    description: Allows you to use the bottlefilling command.
    default: false
  xpShop.buy:
    description: Allows you to buy xp.
    default: false
  xpShop.sell:
    description: Allows you to sell xp.
    default: false
  xpShop.buylevel:
    description: Allows you to buy level.
    default: false
  xpShop.selllevel:
    description: Allows you to sell level.
    default: false
  xpShop.info:
    description: gives you an info.
    default: false
  xpShop.help:
    description: gives you a help.
    default: false
  xpShop.send:
    description: send XP to other players.
    default: false
  xpShop.infoxp.own:
    description: Returns your XP amount.
    default: false
  xpShop.infolevel.own:
    description: Returns your level amount.
    default: false
  xpShop.infoxp.other:
    description: Returns your level amount of any player.
    default: false
  xpShop.infolevel.other:
    description: Returns level amount of any player.
    default: false
  xpShop.internet:
    description: Gives you the ability to change the internet option.
    default: op
  xpShop.version:
    description: Allows you to show the version number of the plugin.
    default: true
  xpShop.debugfile:
    description: Allows you to toggle debuging.
    default: false
  xpShop.admin:
    description: Allows you to do admin stuff.
    default: false
  xpShop.deletetable:
    description: Allows you to delete the xpShop table.
    default: false
  xpShop.resetplayer:
    description: Allows you to resets players XP.
    default: false
  xpShop.setxp:
    description: Allows you to set players xp.
    default: false
  xpShop.showdebug:
    description: Shows you the debug.
    default: false
  xpShop.repair:
    description: Gives you access to the repair command.
    default: false
  xpShop.report:
    description: Gives you access to the report command.
    default: op
  xpShop.toolinfo:
    description: Gives you access to the toolinfo command.
    default: op
  xpShop.grand:
    description: Allows you to grand a mount of XP to a player
    default: false
  xpShop.tpto:
    description: Allows you to teleport to a player for XP
    default: false
  xpShop.tpme:
    description: Allows you to teleport a player to you
    default: false
  xpShop.tp:
    description: Allows you to accept a teleport.
    default: false
  xpShop.update:
    description: Allows you to update the plugin ingame.
    default: false